import React, { Component } from 'react';
import axios from'axios';
import CommentList from './commentList';
import CommentForm from './commentForm';

class CommentBox extends Component {

  constructor(props) {
    super(props);
    this.state = {
      data: []
    };

  }

  loadCommentsFromServer() {
    axios.get(this.props.url)
      .then( response => {
        this.setState({ data: response.data});
      })
      .catch(error => {
        console.log(this.props.url, error);
      });
  }

  handleCommentSubmit (comment) {
    var comments = this.state.data;
    // Optomistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    comment.id = Date.now();
    var newComments = comments.concat([comment]);
    this.setState({date: newComments});

    axios.post(this.props.url, { data: comment })
      .then(response => {
        this.setState({data: response.data});
      })
      .catch(error => {
        console.log(error);
      });
  }
  
  componentDidMount () {
    this.loadCommentsFromServer();
    //setInterval(this.loadCommentsFromServer.bind(this), this.props.pollInterval);
  }

  render() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm onCommentSubmit={this.handleCommentSubmit.bind(this)} />
      </div>
    );
  }
}

export default CommentBox;